import { fileURLToPath, URL } from 'node:url';

import vue from '@vitejs/plugin-vue';

import { defineConfig } from 'vitest/config';

const local = (p) => fileURLToPath(new URL(p, import.meta.url)).replace(/\\/g, '/');

export default defineConfig({
	plugins: [ vue() ],
	resolve: {
		alias: [
			// this package imports its own files by package name
			{ find: /^@thzero\/library_client_vue3\//, replacement: local('./') },
			// supplied by the application's build
			{ find: 'local-config', replacement: local('./test/stubs/config.json') },
			// generated by the application's build
			{ find: 'open-source-config', replacement: local('./test/stubs/openSource.js') }
		],
		// as the applications' vite.config.js: imports name .vue files without the extension
		extensions: [ '.mjs', '.js', '.json', '.vue' ]
	},
	test: {
		environment: 'jsdom',
		// the first import transforms the whole dependency tree, cold
		testTimeout: 30000,
		include: [ 'test/**/*.test.js' ],
		setupFiles: [ 'test/setup.js' ],
		coverage: {
			provider: 'v8',
			reporter: [ 'text-summary', 'lcov' ],
			// every source file, so a file no test loads counts as uncovered
			include: [ '**/*.{js,vue}' ],
			exclude: [ 'test/**', 'coverage/**', '_config/**', '*.config.*', 'openSource.js' ],
			// a ratchet, about 2 points under what was measured on 2026-10-09
			// (statements 47.17, branches 26.83, functions 40.06, lines 46.86);
			// raise these as tests are added, never lower them
			thresholds: { statements: 45, branches: 24, functions: 38, lines: 44 }
		},
		server: {
			deps: {
				// @thzero packages import without file extensions, which Vite resolves
				// but Node does not, so they must be transformed rather than externalized
				inline: [ /@thzero\// ]
			}
		}
	}
});
